#!/bin/bash

for file in $(git diff --diff-filter=d --cached --name-only | grep -E '\.(js|jsx)$')
do
  git show ":$file" | eslint --stdin --stdin-filename "$file" # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    exit 1 # exit with failure status
  fi
done
